
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas.voting }}
  selector:
    matchLabels:
      app: voting
  template:
    metadata:
      labels:
        app: voting
    spec:
      containers:
        - name: voting
          image: {{ .Values.images.voting | quote }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "default"
          readinessProbe:
            httpGet:
              path: /api/origamis
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/origamis
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: voting
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: voting
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
