networks:
  craftista:
    driver: bridge

services:
  frontend:
    image: my/craftista-frontend:dev
    build:
      context: ./services/frontend
    ports:
      - "80:3000"
    networks:
      - craftista

  catalogue:
    image: my/craftista-catalogue:dev
    build:
      context: ./services/catalogue
    ports:
      - "5000:5000"
    networks:
      - craftista
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket; s=socket.socket(); s.settimeout(2); s.connect(('127.0.0.1',5000)); s.close()\""]
      interval: 30s
      timeout: 5s
      retries: 3

  catalogue-db:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops
      POSTGRES_DB: catalogue
    networks:
      - craftista

  recco:
    image: my/craftista-recco:dev
    build:
      context: ./services/recommendation
    ports:
      - "8080:8080"
    networks:
      - craftista

  voting:
    image: my/craftista-voting:dev
    build:
      context: ./services/voting
    ports:
      - "8081:8080"
    depends_on: 
      - catalogue
    networks:
      - craftista

