apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting
  namespace: craftista
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting
  template:
    metadata:
      labels:
        app: voting
    spec:
      containers:
        - name: voting
          image: 132410971191.dkr.ecr.us-east-1.amazonaws.com/craftista-voting:sha-2305f20
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "default"
          readinessProbe:
            httpGet:
              path: /api/origamis
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/origamis
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: voting
  namespace: craftista
spec:
  selector:
    app: voting
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP